DROP DATABASE IF EXISTS test_posts;

CREATE TABLE [IF NOT EXISTS] users (
   id SERIAL PRIMARY KEY,
   firstname VARCHAR(255) NOT NULL,
   lastname VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(100) NOT NULL
);
